version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.apache
    container_name: event_sphere_app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./.env:/var/www/html/.env   # Optional explicit mount
    environment:
      APP_NAME: ${APP_NAME:-Laravel}
      APP_ENV: ${APP_ENV:-local}
      APP_KEY: base64:BTFaOwjbfyRYHugP+VdA80AE5sYJg9BZE6zFDxA1JgY=
      APP_DEBUG: ${APP_DEBUG:-true}
      APP_URL: ${APP_URL:-http://localhost:8000}
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: event_sphere_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel

volumes:
  mysql_data:
